[build]
builder = "nixpacks"

[deploy]
startCommand = "node --no-warnings --experimental-sqlite server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
